name: linter-check
on: push
jobs:
    my-job:
        runs-on: ubuntu-latest
        steps:
         - name: checkout repo
         uses: actions/checkout@v2
         - name: linter-checking
           run: make lint
